import "./globals.css";

export const metadata = {
  title: "Ahi-Llego",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
    },
    shortcut: { url: "/favicon.ico" },
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
